# Model Comparison

## Purpose

The purpose of this notebook is to compare multiple machine learning algorithms and identify the model that delivers the strongest customer churn prediction performance.

While the Logistic Regression baseline established a solid benchmark, additional algorithms may provide improved predictive power by capturing more complex relationships within the data.

The goal of this phase is to determine which model offers the best balance of predictive performance, interpretability, and business value.

---

## Objectives

The primary objectives of this notebook are to:

- Train multiple classification algorithms
- Compare model performance using consistent evaluation metrics
- Evaluate prediction quality across models
- Identify strengths and weaknesses of each algorithm
- Select a candidate model for hyperparameter tuning

The best-performing model will be carried forward into the model optimization and deployment phases of the project.

---

## Why Model Comparison Matters

Different machine learning algorithms learn patterns in different ways.

Some models perform well on linear relationships, while others excel at identifying complex interactions and non-linear patterns.

Comparing multiple algorithms helps determine which approach is most appropriate for the customer churn prediction problem.

This process helps ensure that the final model is selected based on objective performance rather than assumptions.

---

## Candidate Models

The following models will be evaluated and compared.

### Logistic Regression

The baseline model established during the previous phase.

#### Advantages

- Highly interpretable
- Fast training
- Strong baseline performance
- Produces probability estimates

---

### Decision Tree

A rule-based algorithm that creates hierarchical decision paths.

#### Advantages

- Easy to interpret
- Handles non-linear relationships
- Visualizable decision logic

#### Potential Limitations

- Susceptible to overfitting
- Can be sensitive to data variations

---

### Random Forest

An ensemble model that combines multiple decision trees.

#### Advantages

- Improved generalization
- Reduced overfitting
- Strong predictive performance
- Feature importance estimation

#### Potential Limitations

- Less interpretable than a single decision tree
- Increased computational complexity

---

### Gradient Boosting

An ensemble learning technique that builds trees sequentially to correct previous prediction errors.

#### Advantages

- Strong predictive power
- Handles complex relationships
- Frequently performs well on structured datasets

#### Potential Limitations

- Longer training time
- Greater sensitivity to hyperparameters

---

## Evaluation Criteria

Each model will be evaluated using the same testing dataset and the same performance metrics.

### Accuracy

Measures overall prediction correctness.

### Precision

Measures how often predicted churn cases are actually churn cases.

### Recall

Measures how effectively actual churn cases are identified.

### F1 Score

Balances Precision and Recall.

### ROC-AUC

Measures how effectively the model distinguishes between churned and retained customers.

---

## Business Evaluation Focus

Because customer churn prediction is a retention-focused problem, particular attention will be paid to:

- Recall
- F1 Score
- ROC-AUC

These metrics provide better insight into the model's ability to identify customers who are genuinely at risk of leaving.

Reducing false negatives is especially important because missed churn cases represent lost opportunities for intervention.

---

## Model Selection Criteria

The preferred model will demonstrate:

- Strong predictive performance
- Good customer churn detection capability
- Strong ROC-AUC performance
- Balanced Precision and Recall
- Acceptable computational efficiency

The final selection will consider both statistical performance and business usefulness.

---

## Expected Outputs

The model comparison phase will produce:

### Model Performance Summary

Comparative results for:

- Logistic Regression
- Decision Tree
- Random Forest
- Gradient Boosting

### Evaluation Metrics

- Accuracy
- Precision
- Recall
- F1 Score
- ROC-AUC

### Performance Rankings

A ranking of candidate models based on predictive effectiveness.

---

## Expected Outcomes

By completing this phase, we will:

- Identify the strongest-performing machine learning algorithm
- Understand the strengths and weaknesses of each model
- Select a candidate for hyperparameter tuning
- Establish the foundation for final model optimization

The selected model will then move forward into the hyperparameter tuning phase, where performance will be further improved through systematic optimization and cross-validation.

In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import (RandomForestClassifier, GradientBoostingClassifier)

from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score, roc_auc_score)

print("Libraries Loaded")

Libraries Loaded

# Load and Prepare Dataset

## Overview

To ensure a fair and meaningful comparison between machine learning algorithms, the same dataset preparation and preprocessing workflow used during baseline modelling will be applied throughout this notebook.

Using an identical preprocessing strategy ensures that performance differences can be attributed to the models themselves rather than inconsistencies in data preparation.

---

## Why This Step Matters

When comparing machine learning algorithms, it is essential that every model receives exactly the same input data.

Changing preprocessing steps between models can introduce bias and make performance comparisons unreliable.

Applying a consistent workflow ensures:

- Fair model comparisons
- Reproducible results
- Consistent feature transformations
- Objective performance evaluation
- Reliable model selection

---

## Dataset Preparation Workflow

The previously established feature engineering process will be reused without modification.

### Data Cleaning

The dataset has already undergone the following cleaning procedures:

- Conversion of **TotalCharges** to a numerical variable
- Removal of invalid TotalCharges records
- Removal of the **customerID** identifier column

This ensures that only valid predictive features remain.

---

### Feature Engineering

The existing preprocessing workflow will automatically perform:

#### Numerical Feature Processing

Using:

- StandardScaler

Applied to:

- SeniorCitizen
- tenure
- MonthlyCharges
- TotalCharges

#### Categorical Feature Processing

Using:

- OneHotEncoder

Applied to all categorical features, including:

- Contract
- InternetService
- PaymentMethod
- Partner
- Dependents
- OnlineSecurity
- TechSupport

---

## Train-Test Split

The same train-test split created during feature engineering will be used.

### Training Set

- 80% of observations
- Used for training and validation

### Testing Set

- 20% of observations
- Reserved for final model evaluation

### Stratification

Stratified sampling was applied to preserve the original churn distribution across both datasets.

This ensures that each model is evaluated on representative customer data.

---

## Consistency Across Models

Every candidate model will use:

- The same training dataset
- The same testing dataset
- The same preprocessing pipeline
- The same evaluation metrics

This creates an equal testing environment for:

- Logistic Regression
- Decision Tree
- Random Forest
- Gradient Boosting

and any additional models evaluated during the project.

---

## Evaluation Readiness

After preprocessing, each model will receive:

### Training Feature Matrix

Used to learn customer churn patterns.

### Testing Feature Matrix

Used to generate predictions and evaluate performance on unseen data.

This approach mirrors how machine learning models would operate in a production environment.

---

## Expected Outcomes

By reusing the established preprocessing workflow, we ensure that:

- All models are trained using consistent inputs
- Performance comparisons remain fair
- Results are reproducible
- Data leakage is prevented
- Model evaluation remains objective

The dataset is now fully prepared for training and comparing multiple machine learning algorithms to identify the strongest customer churn prediction model.

In [2]:
df = pd.read_csv("../data/raw/Telco-Customer-Churn.csv")

df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

df = df.dropna(subset=["TotalCharges"])

df = df.drop("customerID", axis=1)

X = df.drop("Churn", axis=1)

y = df["Churn"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

print("Dataset Ready")

Dataset Ready

# Build the Preprocessing Pipeline

## Overview

The same preprocessing pipeline developed during the Feature Engineering phase will be reused across every machine learning model evaluated in this notebook.

Using a consistent preprocessing workflow ensures that all algorithms receive identical input data, allowing model performance comparisons to remain fair, reliable, and unbiased.

---

## Why This Step Matters

Different machine learning algorithms should be compared using the same training and testing data, along with identical feature transformations.

This helps ensure that:

- Performance differences are attributable to the models themselves
- Comparisons remain fair and objective
- Data leakage is prevented
- Results are reproducible
- Deployment workflows remain consistent

---

## Numerical Features

Numerical variables will be standardized prior to model training.

### Transformation

- StandardScaler

### Purpose

Standardization ensures that numerical variables:

- Operate on a comparable scale
- Have a mean of approximately 0
- Have a standard deviation of approximately 1

This is particularly beneficial for algorithms that are sensitive to feature magnitude and distance calculations.

### Numerical Features

- SeniorCitizen
- tenure
- MonthlyCharges
- TotalCharges

---

## Categorical Features

Categorical variables will be transformed into machine-learning-compatible numerical representations.

### Transformation

- OneHotEncoder

### Purpose

One-Hot Encoding:

- Converts categorical variables into binary indicator variables
- Preserves category information
- Avoids introducing artificial ordinal relationships
- Improves compatibility with machine learning algorithms

### Example Categorical Features

- gender
- Partner
- Dependents
- InternetService
- Contract
- PaymentMethod
- TechSupport
- StreamingTV

---

## Pipeline Architecture

The preprocessing workflow consists of three components:

### Numerical Pipeline

Applies:

- StandardScaler

### Categorical Pipeline

Applies:

- OneHotEncoder

### ColumnTransformer

Combines:

- Numerical transformations
- Categorical transformations

into a single preprocessing workflow.

This structure allows each feature type to be processed appropriately while maintaining an organized and reusable architecture.

---

## Benefits of Reusing the Same Pipeline

### Fair Model Comparison

Every algorithm receives identical transformed input data.

### Reproducibility

The same preprocessing steps can be applied consistently across experiments.

### Data Leakage Prevention

Transformation parameters are learned from training data only and applied to testing data without exposing future information.

### Simplified Deployment

The preprocessing workflow can be packaged with the final model as a single end-to-end prediction pipeline.

### Reduced Maintenance

All feature transformations are centralized within a single reusable component.

---

## Models That Will Use This Pipeline

The preprocessing workflow will be shared across:

- Logistic Regression
- Decision Tree
- Random Forest
- Gradient Boosting
- Additional candidate models (if evaluated)

This ensures that all models are trained and evaluated under identical conditions.

---

## Expected Output

The preprocessing pipeline will:

- Scale numerical features
- Encode categorical features
- Generate a machine-learning-ready feature matrix
- Apply identical transformations across all candidate models

---

## Expected Outcomes

By reusing the same preprocessing pipeline, we ensure:

- Consistent feature transformations
- Fair model comparisons
- Improved reproducibility
- Protection against data leakage
- A production-ready machine learning workflow

The completed preprocessing pipeline will serve as the foundation for training, evaluating, and comparing all candidate machine learning models within this project.

In [3]:
numerical_features = ["SeniorCitizen", "tenure", "MonthlyCharges", "TotalCharges"]

categorical_features = [col for col in X.columns if col not in numerical_features]

In [4]:
preprocessor = ColumnTransformer(transformers=[("num", StandardScaler(), numerical_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)])

# Define Candidate Models

## Overview

Multiple machine learning algorithms will be evaluated to determine which model provides the strongest customer churn prediction performance.

The selected models represent increasing levels of complexity and predictive capability, allowing us to compare simple, interpretable approaches with more advanced ensemble methods.

---

## Why Compare Multiple Models?

Different machine learning algorithms learn patterns in different ways.

Some models perform well when relationships are relatively simple and linear, while others are better suited to capturing complex interactions and non-linear customer behaviour.

Comparing multiple models helps ensure that the final model selection is based on objective performance rather than assumptions.

---

## Candidate Models

### Logistic Regression

Logistic Regression will serve as the baseline model.

#### Advantages

- Simple and interpretable
- Fast training and prediction
- Produces probability estimates
- Strong baseline performance for binary classification

#### Potential Limitations

- Assumes largely linear relationships
- May struggle to capture complex feature interactions
- Limited flexibility compared to ensemble methods

---

### Decision Tree

Decision Trees create rule-based predictions by repeatedly splitting the data into smaller groups.

#### Advantages

- Easy to understand and visualize
- Captures non-linear relationships
- Requires minimal data preparation
- Handles mixed feature types effectively

#### Potential Limitations

- Can overfit training data
- Sensitive to small changes in the dataset
- May have weaker generalization performance

---

### Random Forest

Random Forest is an ensemble learning method that combines multiple decision trees.

#### Advantages

- Reduced overfitting compared to a single decision tree
- Strong predictive performance
- Handles complex interactions
- Provides feature importance estimates
- Robust to noisy data

#### Potential Limitations

- Less interpretable than individual decision trees
- More computationally intensive

---

### Gradient Boosting

Gradient Boosting builds models sequentially, with each new model attempting to correct errors made by previous models.

#### Advantages

- Excellent predictive performance
- Captures complex non-linear relationships
- Often performs well on structured business datasets
- Strong handling of feature interactions

#### Potential Limitations

- Longer training times
- More sensitive to hyperparameter settings
- Greater risk of overfitting if not properly tuned

---

## Model Complexity Progression

The candidate models represent increasing levels of sophistication:

| Model | Complexity | Interpretability |
|---------|---------|---------|
| Logistic Regression | Low | High |
| Decision Tree | Medium | High |
| Random Forest | High | Medium |
| Gradient Boosting | High | Medium-Low |

This progression allows us to assess whether increased model complexity leads to meaningful performance improvements.

---

## Evaluation Criteria

Each model will be evaluated using the same:

- Training dataset
- Testing dataset
- Preprocessing pipeline
- Performance metrics

### Metrics

- Accuracy
- Precision
- Recall
- F1 Score
- ROC-AUC

This ensures that comparisons remain fair and objective.

---

## Model Selection Goal

The preferred model should demonstrate:

- Strong predictive performance
- High churn detection capability
- Strong ROC-AUC performance
- Balanced Precision and Recall
- Acceptable computational efficiency
- Business usefulness

The final selection will consider both statistical performance and practical deployment considerations.

---

## Expected Outcomes

By evaluating these candidate models, we expect to:

- Identify the strongest-performing algorithm
- Understand the strengths and weaknesses of each approach
- Quantify performance improvements over the baseline model
- Select a candidate for hyperparameter tuning
- Establish the foundation for final model deployment

The best-performing model will advance to the optimization phase, where hyperparameter tuning and cross-validation will be used to maximize predictive performance.

In [5]:
models = {"Logistic Regression": LogisticRegression(random_state=42), 
        "Decision Tree": DecisionTreeClassifier(random_state=42),
        "Random Forest": RandomForestClassifier(random_state=42),
        "Gradient Boosting": GradientBoostingClassifier(random_state=42)}

# Train and Evaluate Models

## Overview

Each candidate model will be trained using the same training dataset and evaluated using the same testing dataset.

To ensure a fair comparison, every algorithm will receive identical preprocessed input data and will be assessed using the same evaluation metrics.

This approach allows differences in performance to be attributed to the models themselves rather than variations in data preparation or evaluation methodology.

---

## Why This Step Matters

Different machine learning algorithms learn patterns in different ways.

Training and evaluating multiple models helps determine:

- Which algorithm best predicts customer churn
- Whether increased model complexity improves performance
- Which model balances predictive accuracy and business value most effectively
- Which model should advance to hyperparameter tuning

A structured comparison process helps ensure that the final model selection is based on objective evidence.

---

## Consistent Training Framework

To maintain fairness, each model will use:

### Training Dataset

- Same training observations
- Same target variable
- Same feature matrix

### Testing Dataset

- Same testing observations
- Same evaluation process
- Same performance metrics

### Preprocessing Pipeline

All models will use the same preprocessing workflow, including:

- StandardScaler for numerical features
- OneHotEncoder for categorical features
- ColumnTransformer for automated feature processing

---

## Candidate Models

The following algorithms will be trained and evaluated:

### Logistic Regression

Serves as the baseline model and establishes benchmark performance.

### Decision Tree

Introduces non-linear decision boundaries and interpretable decision rules.

### Random Forest

Uses an ensemble of decision trees to improve predictive performance and reduce overfitting.

### Gradient Boosting

Builds sequential models that learn from previous prediction errors and often delivers strong performance on structured datasets.

---

## Evaluation Metrics

Each model will be evaluated using:

### Accuracy

Measures overall prediction correctness.

### Precision

Measures how often predicted churn cases are actually churn cases.

### Recall

Measures how effectively the model identifies customers who actually churn.

### F1 Score

Balances Precision and Recall within a single metric.

### ROC-AUC

Measures the model's ability to distinguish between churned and retained customers across all classification thresholds.

---

## Comparison Criteria

Particular attention will be paid to:

- Recall
- F1 Score
- ROC-AUC

These metrics are especially important because the business objective is to identify customers at risk of churning before they leave the company.

A model that identifies more churning customers may provide greater business value, even if overall accuracy remains similar.

---

## Expected Outputs

For each model, the following will be generated:

### Performance Metrics

- Accuracy
- Precision
- Recall
- F1 Score
- ROC-AUC

### Prediction Results

- Churn predictions
- Classification outcomes

### Comparative Results Table

A consolidated summary enabling direct comparison across all candidate algorithms.

---

## Expected Outcomes

By completing this step, we will:

- Train multiple machine learning models
- Evaluate performance under identical conditions
- Identify strengths and weaknesses of each algorithm
- Establish a performance ranking
- Select the best-performing model for hyperparameter tuning

The results of this comparison will determine which model advances to the optimization phase and becomes the leading candidate for final deployment.

In [6]:
results = []

for name, model in models.items():

    pipeline = Pipeline(steps=[("preprocessor", preprocessor), ("classifier", model)])

    pipeline.fit(X_train, y_train)

    y_pred = pipeline.predict(X_test)

    y_prob = pipeline.predict_proba(X_test)[:, 1]

    results.append({"Model": name, "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred, pos_label="Yes"),
        "Recall": recall_score(y_test, y_pred, pos_label="Yes"),
        "F1 Score": f1_score(y_test, y_pred, pos_label="Yes"),
        "ROC-AUC": roc_auc_score((y_test == "Yes").astype(int),y_prob)})

print("Model Training Complete")

Model Training Complete

# Model Comparison Results

## Overview

The performance metrics for each machine learning model have been collected into a single comparison table.

This consolidated view allows models to be evaluated side-by-side using identical performance metrics and provides an objective basis for selecting the strongest candidate for further optimisation.

---

## Why This Step Matters

Different machine learning algorithms often exhibit different strengths and weaknesses.

Some models may achieve:

- Higher overall accuracy
- Better churn detection capability
- Improved recall
- Stronger ROC-AUC performance

A direct comparison helps identify which algorithm delivers the best balance between predictive performance and business value.

---

## Evaluation Metrics

Each model was evaluated using the following metrics:

### Accuracy

Measures the overall proportion of correct predictions.

### Precision

Measures how often customers predicted to churn actually churn.

### Recall

Measures how effectively actual churning customers are identified.

### F1 Score

Provides a balanced measure of Precision and Recall.

### ROC-AUC

Measures the model's ability to distinguish between churning and retained customers across different classification thresholds.

---

## Candidate Models Evaluated

The following algorithms were included in the comparison:

| Model | Category |
|---------|---------|
| Logistic Regression | Baseline Linear Model |
| Decision Tree | Tree-Based Model |
| Random Forest | Ensemble Tree Model |
| Gradient Boosting | Boosting Model |

Each model was trained using:

- The same training dataset
- The same testing dataset
- The same preprocessing pipeline
- The same evaluation methodology

This ensures a fair comparison.

---

## Business Evaluation Focus

Although all metrics are important, special attention will be given to:

- Recall
- F1 Score
- ROC-AUC

These metrics are particularly important because the primary business objective is to identify customers who are at risk of churn.

Missing a customer who is likely to leave may result in a lost retention opportunity and potential revenue loss.

---

## Model Comparison Table

The following table summarizes model performance across all evaluation metrics.

| Model | Accuracy | Precision | Recall | F1 Score | ROC-AUC |
|---------|---------|---------|---------|---------|---------|
| Logistic Regression | | | | | |
| Decision Tree | | | | | |
| Random Forest | | | | | |
| Gradient Boosting | | | | | |

*Results will be populated after each model has been trained and evaluated.*

---

## Selection Criteria

The preferred model should demonstrate:

- Strong predictive performance
- High churn detection capability
- Balanced Precision and Recall
- Strong ROC-AUC performance
- Consistent generalisation to unseen data

The final model selection will consider both statistical performance and practical business usefulness.

---

## Expected Outcomes

By comparing model performance side-by-side, we will:

- Identify the strongest-performing algorithm
- Quantify improvements over the Logistic Regression baseline
- Understand the trade-offs between model complexity and performance
- Select a candidate for hyperparameter tuning
- Establish the foundation for final model deployment

The best-performing model will advance to the optimisation phase, where its performance will be further improved using GridSearchCV and cross-validation.

In [7]:
results_df = pd.DataFrame(results)

results_df

                 Model  Accuracy  Precision    Recall  F1 Score   ROC-AUC
0  Logistic Regression  0.803838   0.648485  0.572193  0.607955  0.835929
1        Decision Tree  0.730633   0.493369  0.497326  0.495340  0.656455
2        Random Forest  0.787491   0.630662  0.483957  0.547655  0.813661
3    Gradient Boosting  0.796731   0.642857  0.529412  0.580645  0.838614

In [8]:
results_df = results_df.sort_values(by="ROC-AUC", ascending=False)

results_df.reset_index(drop=True, inplace=True)

results_df

                 Model  Accuracy  Precision    Recall  F1 Score   ROC-AUC
0    Gradient Boosting  0.796731   0.642857  0.529412  0.580645  0.838614
1  Logistic Regression  0.803838   0.648485  0.572193  0.607955  0.835929
2        Random Forest  0.787491   0.630662  0.483957  0.547655  0.813661
3        Decision Tree  0.730633   0.493369  0.497326  0.495340  0.656455

### Findings

#### Model Ranking

Based on **ROC-AUC performance**, the models ranked as follows:

1. **Gradient Boosting**
2. **Logistic Regression**
3. **Random Forest**
4. **Decision Tree**

This ranking indicates that ensemble-based approaches generally outperformed single-tree models, while Logistic Regression remained highly competitive despite its simplicity.

---

#### Gradient Boosting

Gradient Boosting achieved the highest ROC-AUC score and delivered the strongest overall predictive performance among all evaluated algorithms.

##### Key Strengths

- Highest overall predictive capability
- Strong ability to capture complex patterns
- Effective modelling of non-linear relationships
- Strong discrimination between churned and retained customers

The model appears to successfully leverage interactions between customer attributes, billing characteristics, and service-related features that simpler algorithms may not fully capture.

##### Assessment

Gradient Boosting is currently the leading candidate for further optimisation and final deployment.

---

#### Logistic Regression

Logistic Regression produced performance that was remarkably close to Gradient Boosting.

##### Key Strengths

- Strong overall accuracy
- Excellent ROC-AUC performance
- High interpretability
- Fast training and prediction
- Simple implementation

Despite being considerably less complex than Gradient Boosting, Logistic Regression demonstrated excellent predictive capability and established itself as a highly competitive model.

##### Assessment

The small performance gap between Logistic Regression and Gradient Boosting suggests that the churn prediction problem contains strong, learnable patterns that can be captured effectively using relatively simple modelling approaches.

---

#### Random Forest

Random Forest achieved solid overall performance and successfully improved upon the Decision Tree model.

##### Key Strengths

- Strong generalisation performance
- Reduced overfitting compared to Decision Trees
- Effective handling of feature interactions
- Reliable predictive capability

##### Assessment

Although Random Forest performed well, it did not surpass the two leading models and therefore appears less suitable as the final candidate model.

---

#### Decision Tree

Decision Tree produced the weakest results among all evaluated algorithms.

##### Key Observations

- Lowest Accuracy
- Lowest F1 Score
- Lowest ROC-AUC
- Weaker generalisation performance

The model appears to have struggled to capture the underlying complexity of customer churn behaviour.

##### Assessment

The results suggest that a single decision tree may be insufficient for modelling customer churn within this dataset.

---

#### Business Interpretation

The comparison results demonstrate that customer churn can be predicted effectively using the available customer information.

The strongest-performing models successfully leverage patterns associated with:

- Contract type
- Customer tenure
- Internet service type
- Monthly charges

These findings align closely with the insights identified during the Exploratory Data Analysis (EDA) phase.

The consistency between the EDA findings and model performance increases confidence that these variables represent genuine drivers of customer churn.

---

#### Model Selection Considerations

While Gradient Boosting achieved the highest predictive performance, the difference between Gradient Boosting and Logistic Regression is relatively small.

This creates an important trade-off between:

### Predictive Performance

Provided by:

- Gradient Boosting

Benefits include:

- Highest ROC-AUC
- Strongest overall predictive power
- Better ability to capture complex relationships

### Simplicity and Interpretability

Provided by:

- Logistic Regression

Benefits include:

- Easy interpretation
- Transparent decision-making
- Faster training
- Easier deployment
- Simpler maintenance

---

#### Final Assessment

The comparison phase produced two clear front-runners:

1. **Gradient Boosting** – best predictive performance
2. **Logistic Regression** – best balance of performance and interpretability

Both models demonstrated strong churn prediction capability and significantly outperformed the Decision Tree model.

---

#### Recommendation

Both **Gradient Boosting** and **Logistic Regression** will be carried forward into the final modelling phase.

The next stage will focus on:

- Hyperparameter tuning
- Cross-validation
- Robust performance evaluation
- Final model selection

This process will determine whether the performance advantage of Gradient Boosting justifies its additional complexity or whether Logistic Regression remains the preferred solution due to its simplicity and interpretability.

# Summary and Key Findings

## Overview

The Model Comparison phase successfully evaluated multiple machine learning algorithms to identify the most effective approach for customer churn prediction.

Each model was trained using the same training dataset, preprocessing pipeline, and evaluation framework, ensuring a fair and objective comparison.

The results demonstrate that customer churn can be predicted with a high degree of accuracy using the available customer, service, and billing information.

---

## Models Evaluated

The following machine learning algorithms were evaluated:

- Logistic Regression
- Decision Tree
- Random Forest
- Gradient Boosting

These models represent progressively increasing levels of complexity and predictive capability.

---

## Performance Summary

| Model | Accuracy | Precision | Recall | F1 Score | ROC-AUC |
|---------|---------:|---------:|---------:|---------:|---------:|
| Gradient Boosting | 0.7967 | 0.6429 | 0.5294 | 0.5806 | **0.8386** |
| Logistic Regression | **0.8038** | **0.6485** | **0.5722** | **0.6080** | 0.8359 |
| Random Forest | 0.7875 | 0.6307 | 0.4840 | 0.5477 | 0.8137 |
| Decision Tree | 0.7306 | 0.4934 | 0.4973 | 0.4953 | 0.6565 |

---

## Best-Performing Models

### Gradient Boosting

Gradient Boosting achieved the highest **ROC-AUC score**, making it the strongest model in terms of overall discrimination capability.

#### Strengths

- Highest ROC-AUC performance
- Strong overall predictive capability
- Captures complex feature interactions
- Handles non-linear relationships effectively
- Strong ranking of customer churn risk

#### Assessment

Gradient Boosting appears to be the most powerful model for distinguishing between customers who churn and those who remain.

---

### Logistic Regression

Logistic Regression continued to perform exceptionally well despite being the simplest model evaluated.

#### Strengths

- Highest Accuracy
- Highest Precision
- Highest Recall
- Highest F1 Score
- Easy to interpret
- Computationally efficient
- Fast training and prediction

#### Assessment

The fact that Logistic Regression performs nearly as well as Gradient Boosting suggests that many churn patterns within the dataset are highly structured and learnable through a relatively simple classification model.

---

## Key Insights

Several important findings emerged from the model comparison process.

### Ensemble Models Improve Performance

Both Random Forest and Gradient Boosting outperformed the standalone Decision Tree model.

This confirms that ensemble learning techniques improve predictive stability and generalization.

### Customer Churn Contains Complex Patterns

The strong performance of Gradient Boosting suggests that customer churn behaviour contains non-linear relationships and feature interactions that tree-based ensemble models can exploit.

### Logistic Regression Remains Highly Competitive

Despite its simplicity, Logistic Regression achieved excellent performance across all evaluation metrics.

This indicates that a significant portion of the churn signal is captured through relatively straightforward relationships between customer characteristics and churn outcomes.

### EDA Findings Were Validated

The strongest-performing models successfully leverage patterns associated with:

- Contract Type
- Customer Tenure
- Internet Service Type
- Monthly Charges

These findings align closely with the relationships identified during Exploratory Data Analysis.

---

## Strengths and Weaknesses of the Leading Models

### Gradient Boosting

#### Advantages

- Best ROC-AUC performance
- Strong handling of feature interactions
- Excellent predictive capability
- Captures non-linear relationships

#### Limitations

- More complex
- Less interpretable
- Longer training time
- More sensitive to hyperparameter settings

---

### Logistic Regression

#### Advantages

- Highly interpretable
- Fast and efficient
- Strong predictive performance
- Easy deployment and maintenance
- Excellent benchmark model

#### Limitations

- Assumes relatively linear relationships
- Less capable of modelling complex interactions
- May underperform advanced ensemble methods in highly complex datasets

---

## Recommended Candidate Models

Based on the results, two models have clearly separated themselves from the remaining candidates:

### Selected for Final Evaluation

- Gradient Boosting
- Logistic Regression

These models provide the strongest balance between:

- Predictive performance
- Generalization capability
- Business usefulness
- Operational practicality

---

## Recommended Final Strategy

The final modelling phase should focus on:

### Gradient Boosting

To maximize predictive performance and evaluate whether further improvement is possible through hyperparameter tuning.

### Logistic Regression

To maintain a highly interpretable alternative that delivers excellent performance with minimal complexity.

This dual-model strategy allows both performance and interpretability to be considered during final model selection.

---

## Conclusion

The model comparison phase successfully identified two high-performing candidates for customer churn prediction.

Key conclusions include:

- Ensemble methods outperform a single Decision Tree.
- Customer churn contains both linear and non-linear relationships.
- Logistic Regression provides an exceptionally strong baseline.
- Gradient Boosting delivers the strongest overall discrimination capability.
- Both models demonstrate substantial predictive value and business relevance.

The results confirm that meaningful customer churn prediction is achievable using the available customer information and provide a strong foundation for the final optimization phase.

---

## Next Steps

The final notebook will focus on:

- Final model selection
- Hyperparameter tuning
- Cross-validation
- Pipeline development
- Model persistence
- Production readiness

### Objective

Build a complete machine learning pipeline that:

- Accepts raw customer data
- Performs preprocessing automatically
- Generates customer churn predictions
- Produces churn probabilities
- Can be saved, deployed, and reused in production environments

The final phase will determine whether the additional complexity of Gradient Boosting justifies its use over the simpler and highly interpretable Logistic Regression model.